#端口号
server:
  port: 8001

#服务名spring-cloud使用
spring:
  application:
    name: service-edu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.59.197:3306/edu_online?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456


#mybatis-plus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

